ARG version
FROM almalinux:${version:-9}

ENV  COURSE="Devops" \
     DURATION="120HRS" 
ARG  Trainer="Sivakumar"  

RUN echo "HI, COURSE is ${COURSE},DURATION IS ${DURATION}, TRAINER IS ${Trainer}, version is ${version}"
CMD [ "sleep","1000"]
